const drinks = {
  "Soda Dispenser": {
    Coffee: " bitterness",
    Cola: " cola",
    Cream: " creamy milk",
    "Dr gib": " Cherry Soda",
    Grenadine: " sweet pomegranates",
    Ice: " ice",
    "Iced Tea": " sweet tea",
    "Lemon Juice": " sourness",
    "Lemon Lime": " tangy lime and lemon soda",
    Menthol: " mint",
    "Orange Juice": " oranges",
    "Pwr Game": " sweet and salty tang",
    "SM wind": " sweet citrus soda",
    "Shambler's Juice": " carbonated metallic soda",
    "Soda Water": " carbonated water",
    "Space-up": " cherry soda",
    Sugar: " sweetness",
    Tea: " tart black tea",
    "Tomato Juice": " tomatoes",
    "Tonic Water": " tart and fresh",
    Water: " Water",
  },

  "Booze Dispenser": {
    Absinthe: " death and licorice",
    Ale: " hearty barley ale",
    AppleJack: " an honest day's work at the orchard",
    Beer: " piss water.",
    Cognac: " angry and irish.",
    "Creme de Cacao":
      " a slick and aromatic hint of chocolates swirling in a bite of alcohol.",
    "Creme de Menthe":
      " Minty, cool, and invigorating splash of cold streamwater",
    Gin: " alcoholic christmas tree.",
    "Hard Cider": " the season that <i>falls</i> between summer and winter",
    Kahlua: " alcohol.",
    Rum: " spiked butterscotch.",
    Sake: " sweet rice wine.",
    Tequila: " paint Stripper.",
    "Triple Sec":
      " warm flowery orange taste which recalls the ocean air and summer wind of the caribbean.",
    Vermouth: " dry alcohol.",
    Vodka: " grain alcohol.",
    Whiskey: " molasses.",
    Wine: " bitter sweetness.",
  },

  "Booze-O-Matic": {
    Champagne: " auspicious occasions and bad decisions.",
  },

  "Mixed Drinks": {
    "Acid Spit": " stomach acid",
    Alexander: " bitter, creamy cacao",
    "Allies Cocktail": " bitter yet free",
    Aloe: " sweet 'n creamy",
    Amasec: " dark and metallic",
    Andalusia: " lemons",
    "Anti-freeze": " Jack Frost's piss",
    "Atomic Bomb": " da bomb",
    "B-52": " angry and irish",
    "Bacchus' Blessing": " a wall of bricks",
    "Bahama Mama": " pineapple, coconut, and a hint of coffee",
    "Banana Honk": " a bad joke",
    Barefoot: " creamy berries",
    "Bastion Bourbon": " hot herbal brew with a hint of fruit",
    "Beepsky Smash": " JUSTICE",
    "Between the Sheets": " seduction",
    Bilk: " desperation and lactate",
    "Black Russian": " bitterness",
    "Blank Paper": " bubbling possibility",
    Blazaam: " alternate realities",
    "Bloody Mary": " tomatoes with a hint of lime",
    Booger: " sweet 'n creamy",
    "Branca Menta": " a bitter freshness",
    "Brave Bull": " alcoholic bravery",
    "Bug Spray": " the pain of ten thousand slain mosquitos",
    "Candy corn liquor": " pancake syrup",
    "Changeling Sting": " your brain coming out your nose",
    "Classic Martini": " dry class",
    "Creme de Coconut": " a sweet milky flavor with notes of toasted sugar",
    "Crevice Spike": " a bitter SPIKE with a sour aftertaste",
    "Cuba Libre": " a refreshing marriage of citrus and rum",
    "Demon's Blood": " sweet tasting iron",
    "Devil's Kiss": " bitter iron",
    "Driest Martini": " a beach",
    "Drunken Blumpkin": " molasses and a mouthful of pool water",
    Duplex: " green apples and blue raspberries",
    Eggnog: " custard and alcohol",
    "Erika Surprise": " tartness and bananas",
    Ethanol: " alcohol",
    Fanciulli: " a sweet sobering mix",
    "Fernet Cola": " sweet relief",
    Fernet: " utter bitterness",
    "Fetching Fizz": " charged metal",
    "Fringe Weaver": " ethylic alcohol with a hint of sugar",
    "Fruit Wine": " bad coding",
    "Gin and Tonic": " mild and tart",
    "Gin Fizz": " dry, tart lemons",
    Goldschlager: " burning cinnamon",
    Grappa: " classy bitter sweetness",
    Grasshopper: " chocolate and mint dancing around your mouth",
    "Green Beer": " green piss water",
    Grog: " a poor excuse for alcohol",
    "Hearty Punch": " bravado in the face of disaster",
    "Hippie's Delight": " giving peace a chance",
    Hooch: " pure resignation",
    "Iced Beer": " refreshingly cold",
    "Irish Car Bomb": " delicious anger",
    "Irish Coffee": " giving up on the day",
    "Irish Cream": " creamy alcohol",
    "Jack Rose": " a sweet and sour slice of apple",
    Kamikaze: " divine windiness",
    Kong: " the grip of a giant ape",
    "Light Beer": " dish water",
    "Lizard wine": " scaley sweetness",
    "Long Island Iced Tea": " a mixture of cola and alcohol",
    "Manhattan Project": " death, the destroyer of worlds",
    Manhattan: " mild dryness",
    Margarita: " dry and salty",
    "Mauna Loa": " fiery, with an aftertaste of burnt flesh",
    Mead: " sweet, sweet alcohol",
    Mojito: " refreshing mint",
    Moonshine: " bitterness",
    "Moscow Mule": " refreshing spiciness",
    "Nar'Sour": " bloody",
    Neurotoxin: " a numbing sensation",
    "Old Timer": " simpler times",
    Painkiller: " sugary tartness",
    "Pan-Galactic Gargle Blaster":
      " your brains smashed out by a lemon wrapped around a gold brick",
    Patron: " metallic and expensive",
    "Peppermint Patty": " mint and chocolate",
    "Pina Colada": " pineapple, coconut, and a hint of the ocean",
    "Planet Cracker": " triumph with a hint of bitterness",
    "Quadruple Sec":
      " an invigorating bitter freshness which suffuses your being; no enemy of the station will go unrobusted this day",
    "Quintuple Sec": " THE LAW",
    "Red Mead": " sweet and salty alcohol",
    Rubberneck: " artifical fruityness",
    "Rum and Coke": " cola",
    Sbiten: " hot and spice",
    Screwdriver: " oranges",
    Sidecar: " delicious freedom",
    Silencer: " a pencil eraser",
    Singulo: " concentrated matter",
    "Snow White": " refreshing cold",
    "Squirt Cider": " stale bread with a staler aftertaste",
    Stinger: " a slap on the face in the best possible way",
    "Sugar Rush": " your arteries clogging with sugar",
    "Syndicate Bomb": " purified antagonism",
    "Tequila Sunrise": " oranges with a hint of pomegranate",
    "The Manly Dorf": " hair on your chest and your chin",
    "Thirteen Loko": " jitters and death",
    "Three Mile Island Iced Tea": " dryness",
    "Toxins Special": " spicy toxins",
    "Trappist Beer": " dried plums and malt",
    "Tripe Citrus": " extreme bitterness.",
    Turbo: " the outlaw spirit",
    "Vodka and Tonic": " tart bitterness",
    "Vodka Martini": " shaken, not stirred",
    "Whiskey Cola": " cola",
    "Whiskey Soda": " soda",
    "Whiskey Sour": " sour lemons",
    "White Russian": " bitter cream",
    "Wizz Fizz": " friendship! It is magic, after all",
  },

  "Other Drinking Reagents": {
    "Carrot Juice": " carrots",
    "Berry Juice": " berries",
    "Apple Juice": " apples",
    "Poison Berry Juice": " berries",
    "Watermelon Juice": " juicy watermelon",
    "Banana Juice": " banana",
    Nothing: " nothing",
    Laughter: " laughter",
    "Super Laughter": " laughter",
    "Potato Juice": " irish sadness",
    "Grape Juice": " grape soda",
    Milk: " milk",
    "Soy Milk": " soy milk",
    Lemonade: " sunshine and summertime",
    "Arnold Palmer": " bitter tea",
    "Iced Coffee": " bitter coldness",
    "Iced Tea": " sweet tea",
    "Nuka Cola": " the future",
    "Grey Bull": " carbonated oil",
    "Shambler's Juice": " carbonated metallic soda",
    "Monkey Energy": " barbecue and nostalgia",
    "Soy Latte": " creamy coffee",
    "Cafe Latte": " bitter cream",
    "The Doctor's Delight": " homely fruit",
    "Chocolate Pudding": " sweet chocolate",
    "Vanilla Pudding": " sweet vanilla",
    "Cherry Shake": " creamy cherry",
    "Blue Cherry Shake": " creamy blue cherry",
    "Pumpkin Latte": " creamy pumpkin",
    "Gibb Floats": " creamy cherry",
    "Pumpkin Juice": " pumpkin",
    "Blumpkin Juice": " a mouthful of pool water",
    "Grape soda": " grape soda",
    "Chocolate Milk": " chocolate milk",
    "Hot Coco": " creamy chocolate",
    "Parsnip Juice": " parsnip",
    "Pineapple Juice": " pineapple",
    "Peach Juice": " peaches",
    "Cream Soda": " fizzy vanilla",
    "Sol Dry": " sweet ginger spice",
    "Red Queen": " wonder",
    "Bungo Juice": " succulent bungo",
  },

  "Food Reagents": {
    Consumable: " generic food",
    "Cooking Oil": " oil",
    Sugar: " sweetness",
    "Virus Food": " watery milk",
    Soysauce: " umami",
    Ketchup: " ketchup",
    "Capsaicin Oil": " hot peppers",
    "Frost Oil": " mint",
    "Condensed Capsaicin": " scorching agony",
    "Table Salt": " salt",
    "Black Pepper": " pepper",
    "Coco Powder": " bitterness",
    "Mushroom Hallucinogen": " mushroom",
    "Garlic Juice": " garlic",
    Sprinkles: " childhood whimsy",
    "Corn Oil": " slime",
    "Universal Enzyme": " sweetness",
    "Dry Ramen": " dry and cheap noodles",
    "Hot Ramen": " wet and cheap noodles",
    "Hell Ramen": " wet and cheap noodles on fire",
    Flour: " chalky wheat",
    "Cherry Jelly": " cherry",
    "Blue Cherry Jelly": " blue cherry",
    Rice: " rice",
    "Vanilla Powder": " vanilla",
    "Egg Yolk": " egg",
    "Corn Starch": " slime",
    "Corn Syrup": " sweet slime",
    Honey: " sweetness",
    Mayonnaise: " mayonnaise",
    "Tear Juice": " bitterness",
    "Entropic Polypnium": " bitter mushroom",
    "Tinea Luxor": " tingling mushroom",
    "Vitrium Froth": " fruity mushroom",
    "Clown's Tears": " mournful honking",
    "Liquid Electricity": " pure electricity",
    Astrotame: " sweetness",
    "Secret Sauce": " indescribable",
    Peptides: " mint frosting",
    Caramel: " caramel",
    Char: " smoke",
    "BBQ Sauce": " smokey sweetness",
  },

  "Medicine Reagents": {
    Medicine: " bitterness",
    Adminordrazine: " badmins",
    Quantum: " science",
    Cryoxadone: " sludge",
    Clonexadone: " muscle",
    Pyroxadone: " spicy jelly",
    Rezadone: " fish",
    Saline: " sweetness and salt",
    Calomel: " acid",
    Oculine: " dull toxin",
    Strange: " magnets",
    Mutadone: " acid",
    Antihol: " raw egg",
    Regenerative: " jelly",
    Modafinil: " salt",
    Polypyrylium: " numbing bitterness",
  },

  "Drug Reagents": {
    Drug: " bitterness",
    Nicotine: " smoke",
    "Bath Salts": " salt",
  },

  "Toxin Reagents": {
    Toxin: " bitterness",
    Amatoxin: " mushroom",
    "Unstable mutagen": " slime",
    Plasma: " bitterness",
    Lexorin: " acid",
    "Slime Jelly": " slime",
    "Mint Toxin": " mint",
    Carpotoxin: " fish",
    "Zombie Powder": " death",
    "Ghoul Powder": " death",
    "Mindbreaker Toxin": " sourness",
    "Burning Spore Toxin": " burning",
    "Ground Tea Leaves": " green tea",
    "Mute Toxin": " silence",
    "Bad Food": " bad cooking",
    Lipolicide: " mothballs",
    Spewium: " vomit",
    Rotatium: " spinning",
    "Sulphuric acid": " acid",
    "Mime's Bane": " stillness",
    "Bone Hurting Juice": " bone hurting",
    Bungotoxin: " tannin",
    "Lead Acetate": " sugary sweetness",
  },

  "Cat medicine": {
    Helbital: " cold and lifeless",
    Libital: " bitter with a hint of alcohol",
  },

  "Pyrotechnics Reagents": {
    Thermite: " sweet tasting metal",
    Nitroglycerin: " oil",
    "Stabilizing Agent": " metal",
    "Chlorine Trifluoride": " burning",
    Sorium: " air and bitterness",
    "Liquid Dark Matter": " compressed bitterness",
    Gunpowder: " salt",
    RDX: " salt",
    TaTP: " death",
    "Flash Powder": " salt",
    "Smoke Powder": " smoke",
    "Sonic Powder": " loud noises",
    Phlogiston: " burning",
    Napalm: " burning",
    Cryostylane: " bitterness",
    Pyrosium: " bitterness",
    Teslium: " charged metal",
    "Energized Jelly": " jelly",
    "Firefighting Foam": " the inside of a fire extinguisher",
  },

  "Other Reagents": {
    Blood: " iron",
    "Liquid gibs": " gross iron",
    Vaccine: " slime",
    "Hollow Water": " emptyiness",
    "Hydrogen peroxide": " burning water",
    "Unholy Water": " suffering",
    "Hell Water": " burning",
    "Space Lube": " cherry",
    "Spray Tan": " sour oranges",
    "Stable Mutation Toxin": " slime",
    "Felinid Mutation Toxin": " something nyat good",
    "Lizard Mutation Toxin": " dragon's breath but not as cool",
    "Fly Mutation Toxin": " trash",
    "Moth Mutation Toxin": " clothing",
    "Podperson Mutation Toxin": " flowers",
    "Imperfect Mutation Toxin": " grandma's gelatin",
    "Golem Mutation Toxin": " rocks",
    "Abductor Mutation Toxin": " something out of this world... no, universe!",
    "Android Mutation Toxin": " circuitry and steel",
    "Skeleton Mutation Toxin": " milk... and lots of it",
    "Zombie Mutation Toxin": " brai...nothing in particular",
    "Ash Mutation Toxin": " savagery",
    "Shadow Mutation Toxin": " the night",
    "Plasma Mutation Toxin": " plasma",
    "Mulligan Toxin": " slime",
    "Advanced Mutation Toxin": " slime",
    "Gluttony's Blessing": " decay",
    Serotrotium: " bitterness",
    Copper: " metal",
    Potassium: " sweetness",
    Sulfur: " rotten eggs",
    Carbon: " sour chalk",
    Chlorine: " chlorine",
    Fluorine: " acid",
    Sodium: " salty metal",
    Phosphorus: " vinegar",
    Lithium: " metal",
    Glycerol: " sweetness",
    Sterilizine: " bitterness",
    Iron: " iron",
    Gold: " expensive metal",
    Silver: " expensive yet reasonable metal",
    Uranium: " the inside of a reactor",
    Radium: " the colour blue and regret",
    "Bluespace Dust": " fizzling blue",
    Aluminium: " metal",
    "Welding fuel": " gross metal",
    "Space cleaner": " sourness",
    "EZ Clean": " acid",
    Cryptobiolin: " sourness",
    Impedrezene: " numbness",
    Nanomachines: " sludge",
    Xenomicrobes: " sludge",
    "Tubercle bacillus Cosmosis microbes": " slime",
    "Agent-S": " goo",
    Fluorosurfactant: " metal",
    "Foaming agent": " metal",
    "Smart foaming agent": " metal",
    Ammonia: " mordant",
    Diethylamine: " iron",
    "Carbon Dioxide": " something unknowable",
    "Nitrous Oxide": " sweetness",
    Stimulum: " sourness",
    Nitryl: " burning",
    "Mundane Powder": " the back of class",
    "Generic nutriment": " plant food",
    "Stable Plasma": " bitterness",
    Iodine: " metal",
    Carpet: " carpet",
    "Black Carpet": " licorice",
    "Blue Carpet": " frozen carpet",
    "Cyan Carpet": " asbestos",
    "Green Carpet": " Green",
    "Orange Carpet": " orange juice",
    "Purple Carpet": " jelly",
    "Red Carpet": " blood and gibs",
    "Royal Black Carpet": " royalty",
    "Royal Blue Carpet": " blueyalty",
    Bromine: " chemicals",
    Pentaerythritol: " acid",
    Acetaldehyde: " dead people",
    "Acetone oxide": " acid",
    Phenol: " acid",
    Ash: " ash",
    Acetone: " acid",
    "Colorful Reagent": " rainbows",
    "Quantum Hair Dye": " sourness",
    "Barber's Aid": " sourness",
    "Concentrated Barber's Aid": " sourness",
    Baldium: " bitterness",
    Saltpetre: " cool salt",
    Lye: " acid",
    "Drying agent": " dryness",
    "mutagenic agar": " sourness",
    "sucrose agar": " sweetness",
    "virus rations": " bitterness",
    "virus plasma": " bitterness",
    "weakened virus plasma": " bitterness",
    "decaying uranium gel": " the inside of a reactor",
    "unstable uranium gel": " the inside of a reactor",
    "stable uranium gel": " the inside of a reactor",
    "royal bee jelly": " strange honey",
    Romerol: " brains",
    "Growth Serum": " bitterness",
    "plastic polymers": " plastic",
    "generic glitter": " plastic",
    Pax: " water",
    "BZ metabolites": " acrid cinnamon",
    "Dizzying Solution": " dizziness",
    "Tiring Solution": " tiredness",
    Tranquility: " inner peace",
    "Spider Extract": " upside down",
    "Organic Slurry": " insides",
    "Monkey Powder": " bananas",
  },
};

export default drinks;
