const drinks = [
  {
    category: "Soda Dispenser",
    drinks: [
      { name: "Coffee", flavor: " bitterness" },
      { name: "Cola", flavor: " cola" },
      { name: "Cream", flavor: " creamy milk" },
      { name: "Dr gib", flavor: " Cherry Soda" },
      { name: "Grenadine", flavor: " sweet pomegranates" },
      { name: "Ice", flavor: " ice" },
      { name: "Iced Tea", flavor: " sweet tea" },
      { name: "Lemon Juice", flavor: " sourness" },
      { name: "Lemon Lime", flavor: " tangy lime and lemon soda" },
      { name: "Menthol", flavor: " mint" },
      { name: "Orange Juice", flavor: " oranges" },
      { name: "Pwr Game", flavor: " sweet and salty tang" },
      { name: "SM wind", flavor: " sweet citrus soda" },
      { name: "Shambler's Juice", flavor: " carbonated metallic soda" },
      { name: "Soda Water", flavor: " carbonated water" },
      { name: "Space-up", flavor: " cherry soda" },
      { name: "Sugar", flavor: " sweetness" },
      { name: "Tea", flavor: " tart black tea" },
      { name: "Tomato Juice", flavor: " tomatoes" },
      { name: "Tonic Water", flavor: " tart and fresh" },
      { name: "Water", flavor: " Water" },
    ],
  },

  {
    category: "Booze Dispenser",
    drinks: [
      { name: "Absinthe", flavor: " death and licorice" },
      { name: "Ale", flavor: " hearty barley ale" },
      { name: "AppleJack", flavor: " an honest day's work at the orchard" },
      { name: "Beer", flavor: " piss water" },
      { name: "Cognac", flavor: " angry and irish" },
      {
        name: "Creme de Cacao",
        flavor:
          " a slick and aromatic hint of chocolates swirling in a bite of alcohol",
      },
      {
        name: "Creme de Menthe",
        flavor: " Minty, cool, and invigorating splash of cold streamwater",
      },
      { name: "Gin", flavor: " alcoholic christmas tree" },
      {
        name: "Hard Cider",
        flavor: " the season that <i>falls</i> between summer and winter",
      },
      { name: "Kahlua", flavor: " alcohol" },
      { name: "Rum", flavor: " spiked butterscotch" },
      { name: "Sake", flavor: " sweet rice wine" },
      { name: "Tequila", flavor: " paint Stripper" },
      {
        name: "Triple Sec",
        flavor:
          " warm flowery orange taste which recalls the ocean air and summer wind of the caribbean",
      },
      { name: "Vermouth", flavor: " dry alcohol" },
      { name: "Vodka", flavor: " grain alcohol" },
      { name: "Whiskey", flavor: " molasses" },
      { name: "Wine", flavor: " bitter sweetness" },
    ],
  },

  {
    category: "Booze-O-Matic",
    drinks: [
      { name: "Champagne", flavor: " auspicious occasions and bad decisions" },
    ],
  },

  {
    category: "Mixed Drinks",
    drinks: [
      { name: "Acid Spit", flavor: " stomach acid" },
      { name: "Alexander", flavor: " bitter, creamy cacao" },
      { name: "Allies Cocktail", flavor: " bitter yet free" },
      { name: "Aloe", flavor: " sweet 'n creamy" },
      { name: "Amasec", flavor: " dark and metallic" },
      { name: "Andalusia", flavor: " lemons" },
      { name: "Anti-freeze", flavor: " Jack Frost's piss" },
      { name: "Atomic Bomb", flavor: " da bomb" },
      { name: "B-52", flavor: " angry and irish" },
      { name: "Bacchus' Blessing", flavor: " a wall of bricks" },
      {
        name: "Bahama Mama",
        flavor: " pineapple, coconut, and a hint of coffee",
      },
      { name: "Banana Honk", flavor: " a bad joke" },
      { name: "Barefoot", flavor: " creamy berries" },
      {
        name: "Bastion Bourbon",
        flavor: " hot herbal brew with a hint of fruit",
      },
      { name: "Beepsky Smash", flavor: " JUSTICE" },
      { name: "Between the Sheets", flavor: " seduction" },
      { name: "Bilk", flavor: " desperation and lactate" },
      { name: "Black Russian", flavor: " bitterness" },
      { name: "Blank Paper", flavor: " bubbling possibility" },
      { name: "Blazaam", flavor: " alternate realities" },
      { name: "Bloody Mary", flavor: " tomatoes with a hint of lime" },
      { name: "Booger", flavor: " sweet 'n creamy" },
      { name: "Branca Menta", flavor: " a bitter freshness" },
      { name: "Brave Bull", flavor: " alcoholic bravery" },
      {
        name: "Bug Spray",
        flavor: " the pain of ten thousand slain mosquitos",
      },
      { name: "Candy corn liquor", flavor: " pancake syrup" },
      { name: "Changeling Sting", flavor: " your brain coming out your nose" },
      { name: "Classic Martini", flavor: " dry class" },
      {
        name: "Creme de Coconut",
        flavor: " a sweet milky flavor with notes of toasted sugar",
      },
      {
        name: "Crevice Spike",
        flavor: " a bitter SPIKE with a sour aftertaste",
      },
      {
        name: "Cuba Libre",
        flavor: " a refreshing marriage of citrus and rum",
      },
      { name: "Demon's Blood", flavor: " sweet tasting iron" },
      { name: "Devil's Kiss", flavor: " bitter iron" },
      { name: "Driest Martini", flavor: " a beach" },
      {
        name: "Drunken Blumpkin",
        flavor: " molasses and a mouthful of pool water",
      },
      { name: "Duplex", flavor: " green apples and blue raspberries" },
      { name: "Eggnog", flavor: " custard and alcohol" },
      { name: "Erika Surprise", flavor: " tartness and bananas" },
      { name: "Ethanol", flavor: " alcohol" },
      { name: "Fanciulli", flavor: " a sweet sobering mix" },
      { name: "Fernet Cola", flavor: " sweet relief" },
      { name: "Fernet", flavor: " utter bitterness" },
      { name: "Fetching Fizz", flavor: " charged metal" },
      {
        name: "Fringe Weaver",
        flavor: " ethylic alcohol with a hint of sugar",
      },
      { name: "Fruit Wine", flavor: " bad coding" },
      { name: "Gin and Tonic", flavor: " mild and tart" },
      { name: "Gin Fizz", flavor: " dry, tart lemons" },
      { name: "Goldschlager", flavor: " burning cinnamon" },
      { name: "Grappa", flavor: " classy bitter sweetness" },
      {
        name: "Grasshopper",
        flavor: " chocolate and mint dancing around your mouth",
      },
      { name: "Green Beer", flavor: " green piss water" },
      { name: "Grog", flavor: " a poor excuse for alcohol" },
      { name: "Hearty Punch", flavor: " bravado in the face of disaster" },
      { name: "Hippie's Delight", flavor: " giving peace a chance" },
      { name: "Hooch", flavor: " pure resignation" },
      { name: "Iced Beer", flavor: " refreshingly cold" },
      { name: "Irish Car Bomb", flavor: " delicious anger" },
      { name: "Irish Coffee", flavor: " giving up on the day" },
      { name: "Irish Cream", flavor: " creamy alcohol" },
      { name: "Jack Rose", flavor: " a sweet and sour slice of apple" },
      { name: "Kamikaze", flavor: " divine windiness" },
      { name: "Kong", flavor: " the grip of a giant ape" },
      { name: "Light Beer", flavor: " dish water" },
      { name: "Lizard wine", flavor: " scaley sweetness" },
      {
        name: "Long Island Iced Tea",
        flavor: " a mixture of cola and alcohol",
      },
      { name: "Manhattan Project", flavor: " death, the destroyer of worlds" },
      { name: "Manhattan", flavor: " mild dryness" },
      { name: "Margarita", flavor: " dry and salty" },
      {
        name: "Mauna Loa",
        flavor: " fiery, with an aftertaste of burnt flesh",
      },
      { name: "Mead", flavor: " sweet, sweet alcohol" },
      { name: "Mojito", flavor: " refreshing mint" },
      { name: "Moonshine", flavor: " bitterness" },
      { name: "Moscow Mule", flavor: " refreshing spiciness" },
      { name: "Nar'Sour", flavor: " bloody" },
      { name: "Neurotoxin", flavor: " a numbing sensation" },
      { name: "Old Timer", flavor: " simpler times" },
      { name: "Painkiller", flavor: " sugary tartness" },
      {
        name: "Pan-Galactic Gargle Blaster",
        flavor:
          " your brains smashed out by a lemon wrapped around a gold brick",
      },
      { name: "Patron", flavor: " metallic and expensive" },
      { name: "Peppermint Patty", flavor: " mint and chocolate" },
      {
        name: "Pina Colada",
        flavor: " pineapple, coconut, and a hint of the ocean",
      },
      { name: "Planet Cracker", flavor: " triumph with a hint of bitterness" },
      {
        name: "Quadruple Sec",
        flavor:
          " an invigorating bitter freshness which suffuses your being; no enemy of the station will go unrobusted this day",
      },
      { name: "Quintuple Sec", flavor: " THE LAW" },
      { name: "Red Mead", flavor: " sweet and salty alcohol" },
      { name: "Rubberneck", flavor: " artifical fruityness" },
      { name: "Rum and Coke", flavor: " cola" },
      { name: "Sbiten", flavor: " hot and spice" },
      { name: "Screwdriver", flavor: " oranges" },
      { name: "Sidecar", flavor: " delicious freedom" },
      { name: "Silencer", flavor: " a pencil eraser" },
      { name: "Singulo", flavor: " concentrated matter" },
      { name: "Snow White", flavor: " refreshing cold" },
      { name: "Squirt Cider", flavor: " stale bread with a staler aftertaste" },
      {
        name: "Stinger",
        flavor: " a slap on the face in the best possible way",
      },
      { name: "Sugar Rush", flavor: " your arteries clogging with sugar" },
      { name: "Syndicate Bomb", flavor: " purified antagonism" },
      {
        name: "Tequila Sunrise",
        flavor: " oranges with a hint of pomegranate",
      },
      { name: "The Manly Dorf", flavor: " hair on your chest and your chin" },
      { name: "Thirteen Loko", flavor: " jitters and death" },
      { name: "Three Mile Island Iced Tea", flavor: " dryness" },
      { name: "Toxins Special", flavor: " spicy toxins" },
      { name: "Trappist Beer", flavor: " dried plums and malt" },
      { name: "Tripe Citrus", flavor: " extreme bitterness" },
      { name: "Turbo", flavor: " the outlaw spirit" },
      { name: "Vodka and Tonic", flavor: " tart bitterness" },
      { name: "Vodka Martini", flavor: " shaken, not stirred" },
      { name: "Whiskey Cola", flavor: " cola" },
      { name: "Whiskey Soda", flavor: " soda" },
      { name: "Whiskey Sour", flavor: " sour lemons" },
      { name: "White Russian", flavor: " bitter cream" },
      { name: "Wizz Fizz", flavor: " friendship! It is magic, after all" },
    ],
  },

  {
    category: "Other Drinking Reagents",
    drinks: [
      { name: "Carrot Juice", flavor: " carrots" },
      { name: "Berry Juice", flavor: " berries" },
      { name: "Apple Juice", flavor: " apples" },
      { name: "Poison Berry Juice", flavor: " berries" },
      { name: "Watermelon Juice", flavor: " juicy watermelon" },
      { name: "Banana Juice", flavor: " banana" },
      { name: "Nothing", flavor: " nothing" },
      { name: "Laughter", flavor: " laughter" },
      { name: "Super Laughter", flavor: " laughter" },
      { name: "Potato Juice", flavor: " irish sadness" },
      { name: "Grape Juice", flavor: " grape soda" },
      { name: "Milk", flavor: " milk" },
      { name: "Soy Milk", flavor: " soy milk" },
      { name: "Lemonade", flavor: " sunshine and summertime" },
      { name: "Arnold Palmer", flavor: " bitter tea" },
      { name: "Iced Coffee", flavor: " bitter coldness" },
      { name: "Iced Tea", flavor: " sweet tea" },
      { name: "Nuka Cola", flavor: " the future" },
      { name: "Grey Bull", flavor: " carbonated oil" },
      { name: "Shambler's Juice", flavor: " carbonated metallic soda" },
      { name: "Monkey Energy", flavor: " barbecue and nostalgia" },
      { name: "Soy Latte", flavor: " creamy coffee" },
      { name: "Cafe Latte", flavor: " bitter cream" },
      { name: "The Doctor's Delight", flavor: " homely fruit" },
      { name: "Chocolate Pudding", flavor: " sweet chocolate" },
      { name: "Vanilla Pudding", flavor: " sweet vanilla" },
      { name: "Cherry Shake", flavor: " creamy cherry" },
      { name: "Blue Cherry Shake", flavor: " creamy blue cherry" },
      { name: "Pumpkin Latte", flavor: " creamy pumpkin" },
      { name: "Gibb Floats", flavor: " creamy cherry" },
      { name: "Pumpkin Juice", flavor: " pumpkin" },
      { name: "Blumpkin Juice", flavor: " a mouthful of pool water" },
      { name: "Grape soda", flavor: " grape soda" },
      { name: "Chocolate Milk", flavor: " chocolate milk" },
      { name: "Hot Coco", flavor: " creamy chocolate" },
      { name: "Parsnip Juice", flavor: " parsnip" },
      { name: "Pineapple Juice", flavor: " pineapple" },
      { name: "Peach Juice", flavor: " peaches" },
      { name: "Cream Soda", flavor: " fizzy vanilla" },
      { name: "Sol Dry", flavor: " sweet ginger spice" },
      { name: "Red Queen", flavor: " wonder" },
      { name: "Bungo Juice", flavor: " succulent bungo" },
    ],
  },

  {
    category: "Food Reagents",
    drinks: [
      { name: "Consumable", flavor: " generic food" },
      { name: "Cooking Oil", flavor: " oil" },
      { name: "Sugar", flavor: " sweetness" },
      { name: "Virus Food", flavor: " watery milk" },
      { name: "Soysauce", flavor: " umami" },
      { name: "Ketchup", flavor: " ketchup" },
      { name: "Capsaicin Oil", flavor: " hot peppers" },
      { name: "Frost Oil", flavor: " mint" },
      { name: "Condensed Capsaicin", flavor: " scorching agony" },
      { name: "Table Salt", flavor: " salt" },
      { name: "Black Pepper", flavor: " pepper" },
      { name: "Coco Powder", flavor: " bitterness" },
      { name: "Mushroom Hallucinogen", flavor: " mushroom" },
      { name: "Garlic Juice", flavor: " garlic" },
      { name: "Sprinkles", flavor: " childhood whimsy" },
      { name: "Corn Oil", flavor: " slime" },
      { name: "Universal Enzyme", flavor: " sweetness" },
      { name: "Dry Ramen", flavor: " dry and cheap noodles" },
      { name: "Hot Ramen", flavor: " wet and cheap noodles" },
      { name: "Hell Ramen", flavor: " wet and cheap noodles on fire" },
      { name: "Flour", flavor: " chalky wheat" },
      { name: "Cherry Jelly", flavor: " cherry" },
      { name: "Blue Cherry Jelly", flavor: " blue cherry" },
      { name: "Rice", flavor: " rice" },
      { name: "Vanilla Powder", flavor: " vanilla" },
      { name: "Egg Yolk", flavor: " egg" },
      { name: "Corn Starch", flavor: " slime" },
      { name: "Corn Syrup", flavor: " sweet slime" },
      { name: "Honey", flavor: " sweetness" },
      { name: "Mayonnaise", flavor: " mayonnaise" },
      { name: "Tear Juice", flavor: " bitterness" },
      { name: "Entropic Polypnium", flavor: " bitter mushroom" },
      { name: "Tinea Luxor", flavor: " tingling mushroom" },
      { name: "Vitrium Froth", flavor: " fruity mushroom" },
      { name: "Clown's Tears", flavor: " mournful honking" },
      { name: "Liquid Electricity", flavor: " pure electricity" },
      { name: "Astrotame", flavor: " sweetness" },
      { name: "Secret Sauce", flavor: " indescribable" },
      { name: "Peptides", flavor: " mint frosting" },
      { name: "Caramel", flavor: " caramel" },
      { name: "Char", flavor: " smoke" },
      { name: "BBQ Sauce", flavor: " smokey sweetness" },
    ],
  },

  {
    category: "Medicine Reagents",
    drinks: [
      { name: "Medicine", flavor: " bitterness" },
      { name: "Adminordrazine", flavor: " badmins" },
      { name: "Quantum", flavor: " science" },
      { name: "Cryoxadone", flavor: " sludge" },
      { name: "Clonexadone", flavor: " muscle" },
      { name: "Pyroxadone", flavor: " spicy jelly" },
      { name: "Rezadone", flavor: " fish" },
      { name: "Saline", flavor: " sweetness and salt" },
      { name: "Calomel", flavor: " acid" },
      { name: "Oculine", flavor: " dull toxin" },
      { name: "Strange", flavor: " magnets" },
      { name: "Mutadone", flavor: " acid" },
      { name: "Antihol", flavor: " raw egg" },
      { name: "Regenerative", flavor: " jelly" },
      { name: "Modafinil", flavor: " salt" },
      { name: "Polypyrylium", flavor: " numbing bitterness" },
    ],
  },

  {
    category: "Drug Reagents",
    drinks: [
      { name: "Drug", flavor: " bitterness" },
      { name: "Nicotine", flavor: " smoke" },
      { name: "Bath Salts", flavor: " salt" },
    ],
  },

  {
    category: "Toxin Reagents",
    drinks: [
      { name: "Toxin", flavor: " bitterness" },
      { name: "Amatoxin", flavor: " mushroom" },
      { name: "Unstable mutagen", flavor: " slime" },
      { name: "Plasma", flavor: " bitterness" },
      { name: "Lexorin", flavor: " acid" },
      { name: "Slime Jelly", flavor: " slime" },
      { name: "Mint Toxin", flavor: " mint" },
      { name: "Carpotoxin", flavor: " fish" },
      { name: "Zombie Powder", flavor: " death" },
      { name: "Ghoul Powder", flavor: " death" },
      { name: "Mindbreaker Toxin", flavor: " sourness" },
      { name: "Burning Spore Toxin", flavor: " burning" },
      { name: "Ground Tea Leaves", flavor: " green tea" },
      { name: "Mute Toxin", flavor: " silence" },
      { name: "Bad Food", flavor: " bad cooking" },
      { name: "Lipolicide", flavor: " mothballs" },
      { name: "Spewium", flavor: " vomit" },
      { name: "Rotatium", flavor: " spinning" },
      { name: "Sulphuric acid", flavor: " acid" },
      { name: "Mime's Bane", flavor: " stillness" },
      { name: "Bone Hurting Juice", flavor: " bone hurting" },
      { name: "Bungotoxin", flavor: " tannin" },
      { name: "Lead Acetate", flavor: " sugary sweetness" },
    ],
  },

  {
    category: "Cat medicine",
    drinks: [
      { name: "Helbital", flavor: " cold and lifeless" },
      { name: "Libital", flavor: " bitter with a hint of alcohol" },
    ],
  },

  {
    category: "Pyrotechnics Reagents",
    drinks: [
      { name: "Thermite", flavor: " sweet tasting metal" },
      { name: "Nitroglycerin", flavor: " oil" },
      { name: "Stabilizing Agent", flavor: " metal" },
      { name: "Chlorine Trifluoride", flavor: " burning" },
      { name: "Sorium", flavor: " air and bitterness" },
      { name: "Liquid Dark Matter", flavor: " compressed bitterness" },
      { name: "Gunpowder", flavor: " salt" },
      { name: "RDX", flavor: " salt" },
      { name: "TaTP", flavor: " death" },
      { name: "Flash Powder", flavor: " salt" },
      { name: "Smoke Powder", flavor: " smoke" },
      { name: "Sonic Powder", flavor: " loud noises" },
      { name: "Phlogiston", flavor: " burning" },
      { name: "Napalm", flavor: " burning" },
      { name: "Cryostylane", flavor: " bitterness" },
      { name: "Pyrosium", flavor: " bitterness" },
      { name: "Teslium", flavor: " charged metal" },
      { name: "Energized Jelly", flavor: " jelly" },
      {
        name: "Firefighting Foam",
        flavor: " the inside of a fire extinguisher",
      },
    ],
  },

  {
    category: "Other Reagents",
    drinks: [
      { name: "Blood", flavor: " iron" },
      { name: "Liquid gibs", flavor: " gross iron" },
      { name: "Vaccine", flavor: " slime" },
      { name: "Hollow Water", flavor: " emptyiness" },
      { name: "Hydrogen peroxide", flavor: " burning water" },
      { name: "Unholy Water", flavor: " suffering" },
      { name: "Hell Water", flavor: " burning" },
      { name: "Space Lube", flavor: " cherry" },
      { name: "Spray Tan", flavor: " sour oranges" },
      { name: "Stable Mutation Toxin", flavor: " slime" },
      { name: "Felinid Mutation Toxin", flavor: " something nyat good" },
      {
        name: "Lizard Mutation Toxin",
        flavor: " dragon's breath but not as cool",
      },
      { name: "Fly Mutation Toxin", flavor: " trash" },
      { name: "Moth Mutation Toxin", flavor: " clothing" },
      { name: "Podperson Mutation Toxin", flavor: " flowers" },
      { name: "Imperfect Mutation Toxin", flavor: " grandma's gelatin" },
      { name: "Golem Mutation Toxin", flavor: " rocks" },
      {
        name: "Abductor Mutation Toxin",
        flavor: " something out of this world no, universe!",
      },
      { name: "Android Mutation Toxin", flavor: " circuitry and steel" },
      { name: "Skeleton Mutation Toxin", flavor: " milk and lots of it" },
      {
        name: "Zombie Mutation Toxin",
        flavor: " brainothing in particular",
      },
      { name: "Ash Mutation Toxin", flavor: " savagery" },
      { name: "Shadow Mutation Toxin", flavor: " the night" },
      { name: "Plasma Mutation Toxin", flavor: " plasma" },
      { name: "Mulligan Toxin", flavor: " slime" },
      { name: "Advanced Mutation Toxin", flavor: " slime" },
      { name: "Gluttony's Blessing", flavor: " decay" },
      { name: "Serotrotium", flavor: " bitterness" },
      { name: "Copper", flavor: " metal" },
      { name: "Potassium", flavor: " sweetness" },
      { name: "Sulfur", flavor: " rotten eggs" },
      { name: "Carbon", flavor: " sour chalk" },
      { name: "Chlorine", flavor: " chlorine" },
      { name: "Fluorine", flavor: " acid" },
      { name: "Sodium", flavor: " salty metal" },
      { name: "Phosphorus", flavor: " vinegar" },
      { name: "Lithium", flavor: " metal" },
      { name: "Glycerol", flavor: " sweetness" },
      { name: "Sterilizine", flavor: " bitterness" },
      { name: "Iron", flavor: " iron" },
      { name: "Gold", flavor: " expensive metal" },
      { name: "Silver", flavor: " expensive yet reasonable metal" },
      { name: "Uranium", flavor: " the inside of a reactor" },
      { name: "Radium", flavor: " the colour blue and regret" },
      { name: "Bluespace Dust", flavor: " fizzling blue" },
      { name: "Aluminium", flavor: " metal" },
      { name: "Welding fuel", flavor: " gross metal" },
      { name: "Space cleaner", flavor: " sourness" },
      { name: "EZ Clean", flavor: " acid" },
      { name: "Cryptobiolin", flavor: " sourness" },
      { name: "Impedrezene", flavor: " numbness" },
      { name: "Nanomachines", flavor: " sludge" },
      { name: "Xenomicrobes", flavor: " sludge" },
      { name: "Tubercle bacillus Cosmosis microbes", flavor: " slime" },
      { name: "Agent-S", flavor: " goo" },
      { name: "Fluorosurfactant", flavor: " metal" },
      { name: "Foaming agent", flavor: " metal" },
      { name: "Smart foaming agent", flavor: " metal" },
      { name: "Ammonia", flavor: " mordant" },
      { name: "Diethylamine", flavor: " iron" },
      { name: "Carbon Dioxide", flavor: " something unknowable" },
      { name: "Nitrous Oxide", flavor: " sweetness" },
      { name: "Stimulum", flavor: " sourness" },
      { name: "Nitryl", flavor: " burning" },
      { name: "Mundane Powder", flavor: " the back of class" },
      { name: "Generic nutriment", flavor: " plant food" },
      { name: "Stable Plasma", flavor: " bitterness" },
      { name: "Iodine", flavor: " metal" },
      { name: "Carpet", flavor: " carpet" },
      { name: "Black Carpet", flavor: " licorice" },
      { name: "Blue Carpet", flavor: " frozen carpet" },
      { name: "Cyan Carpet", flavor: " asbestos" },
      { name: "Green Carpet", flavor: " Green" },
      { name: "Orange Carpet", flavor: " orange juice" },
      { name: "Purple Carpet", flavor: " jelly" },
      { name: "Red Carpet", flavor: " blood and gibs" },
      { name: "Royal Black Carpet", flavor: " royalty" },
      { name: "Royal Blue Carpet", flavor: " blueyalty" },
      { name: "Bromine", flavor: " chemicals" },
      { name: "Pentaerythritol", flavor: " acid" },
      { name: "Acetaldehyde", flavor: " dead people" },
      { name: "Acetone oxide", flavor: " acid" },
      { name: "Phenol", flavor: " acid" },
      { name: "Ash", flavor: " ash" },
      { name: "Acetone", flavor: " acid" },
      { name: "Colorful Reagent", flavor: " rainbows" },
      { name: "Quantum Hair Dye", flavor: " sourness" },
      { name: "Barber's Aid", flavor: " sourness" },
      { name: "Concentrated Barber's Aid", flavor: " sourness" },
      { name: "Baldium", flavor: " bitterness" },
      { name: "Saltpetre", flavor: " cool salt" },
      { name: "Lye", flavor: " acid" },
      { name: "Drying agent", flavor: " dryness" },
      { name: "mutagenic agar", flavor: " sourness" },
      { name: "sucrose agar", flavor: " sweetness" },
      { name: "virus rations", flavor: " bitterness" },
      { name: "virus plasma", flavor: " bitterness" },
      { name: "weakened virus plasma", flavor: " bitterness" },
      { name: "decaying uranium gel", flavor: " the inside of a reactor" },
      { name: "unstable uranium gel", flavor: " the inside of a reactor" },
      { name: "stable uranium gel", flavor: " the inside of a reactor" },
      { name: "royal bee jelly", flavor: " strange honey" },
      { name: "Romerol", flavor: " brains" },
      { name: "Growth Serum", flavor: " bitterness" },
      { name: "plastic polymers", flavor: " plastic" },
      { name: "generic glitter", flavor: " plastic" },
      { name: "Pax", flavor: " water" },
      { name: "BZ metabolites", flavor: " acrid cinnamon" },
      { name: "Dizzying Solution", flavor: " dizziness" },
      { name: "Tiring Solution", flavor: " tiredness" },
      { name: "Tranquility", flavor: " inner peace" },
      { name: "Spider Extract", flavor: " upside down" },
      { name: "Organic Slurry", flavor: " insides" },
      { name: "Monkey Powder", flavor: " bananas" },
    ],
  },
];
